# bulk_import_clients.py

from models.client import Client
# db.py

import mongoengine 

mongoengine.connect(host='mongodb+srv://user:user@cluster0.rgocxdb.mongodb.net/abhi_orm')
client_names = [
"Aaradhya Silks",
"Acela Services",
"Adnaan Textiles",
"Agarwal Saree India Private Limited",
"Akshaya Silks",
"AKT Textiles",
"Akula Chiranjeevulu and Co",
"Alladi Veeresham",
"Ambica Silk Palace",
"Ambica Silks",
"Amurdham Cloth Traders",
"Anand Kumar D.K",
"Anand Shopping Mall",
"Anand Silks Nellore",
"Andela Textiles Pvt Ltd",
"Anutex Shopping Mall LLP",
"Aradhana Textiles",
"Aruna Silk House",
"Aruna Silks",
"Arya Collections",
"Ashoka",
"Ashok Silks",
"Balaji Silk Hubli",
"Baratam Brothers",
"Best One",
"Bhadarakali Sarees",
"Bharathi Textiles",
"Bharat Silk Sarees",
"Bhawani Hi Fashion",
"Bombay Cloth House",
"BS Gupta Exclusive",
"BSR Textiles",
"CB Agros Shopping Mall",
"Chandana Brothers",
"Chandra Shopping Mall",
"Chetan Silks",
"Colourss",
"CS Brothers",
"Damodar Silks and Sarees",
"Dasari Silk House",
"Dasari Sunitha Raj",
"Deepa Silks",
"Devanand Silk Sarees",
"Dhanalakshmi Cloth Hall",
"Dhanalakshmi Silks",
"Divya Lakshmi Vastralayam",
"Divyathej Creations",
"Dontha Brothers Sarees",
"Durga Bhavani Traders",
"Durga Textile Agency",
"Embellis Sarees Private Limited",
"Fashion House",
"Gandham Silks",
"Ganduri Brothers",
"Gangavathi Silk Palace",
"Gangotri Silk House",
"Gayatri Sarees",
"GBL Corporation",
"Geetha Sarees",
"Geetha Silk Sarees",
"Gopi Krishna Shopping Mall",
"GR Silks",
"GVT Pvt Ltd",
"Habib Silk and Sarees",
"Haneef Brothers",
"Harideep Shopping Mall",
"Harikrishna Cloth Centre",
"HM Silks",
"Isha Creations",
"Jaiguru Creation",
"Jaju Sarees Private Limited",
"Jalla Sai Ganesh",
"Jinka Maangalya Silks",
"JK Cloth Stores",
"JK Silks",
"JK Textiles",
"Jogulamba Silks",
"Jyothi Silk and Sarees",
"Kabra Sales Corporation",
"Kamal Wedding Mall",
"Kanchi Silks",
"Kanmani Exporters",
"Kasam Fashion Mall",
"Kasam Sambamurthy Sarees",
"Kasturi Textiles",
"Kavade Silk Sarees",
"Kavitha Wedding Mall",
"KDM Silks",
"Kimara Fashions",
"Kisan",
"KM Fashions",
"KPavan Kumar",
"KSR Textiles",
"KSV Mehtaj Showroom",
"KV Tex",
"Lakshmi Vasavi Silks",
"Lalitha Kala Silks",
"Lavanya Shopping Mall",
"Laxmi Narasimha Swamy Silks",
"Laxmi Silks",
"Liyaa Silks and Sarees",
"Maanav Trading Co",
"Maangalya Shopping Mall",
"Madhu Fashion",
"Mahaa Collections",
"Mahasiva Silks",
"Maheshwari Silks Sarees",
"Mamatha Silk Centre",
"Man Mandir Trade Centre",
"Mansi NX",
"Mantra Sarees",
"Maruthi Textiles",
"Mayura Silks",
"MBR Shopping Mall",
"Mohan Textiles",
"Charugundla Muthaiah Sons",
"Hima Sai Fabrics",
"Kandukuri Lifestyle Pvt Ltd",
"Shree Handlooms",
"Swapna Sarees Center",
"Nagamani Cloth Shop",
"Nandini Sarees",
"Naresh Textiles",
"New Bharat Fancy",
"New Krishnaarjuna Textiles",
"New Madras Sarees",
"Nirmala Silks",
"Om Pavan Shopping Mall",
"Pardhus BSR Group",
"Parvathi Enterprises",
"Pooja Matching Center",
"Poombukar Fashions",
"Prakash Silk Palace",
"PSK Textiles",
"PSR Silk Sarees India Pvt Ltd",
"Puja Silks",
"Purna Chandra Silk House",
"PV Designer Studio",
"Radhika Cut Pieces",
"Rajamundry Cutpiece Centre",
"Rajamundry Saree Mandir",
"Rajasthan Silk Sarees",
"Rajeshwari Silks",
"Raj Kamal",
"Ramesh Textiles",
"Ram Lakshman Silk Showroom",
"Ratan Silk Sarees",
"Reddy Bros",
"Rekha Shopping Mall",
"Reliance Retail Limited",
"RK Clothing",
"RK Fashions",
"RK Shopping Mall",
"RK Stores",
"RK Textiles",
"RK Vastra Nidhi",
"RMKV Silks Pvt Ltd",
"Roop Laxmi Kanchi Mandir",
"Ramalingam and Sons",
"RR Creations",
"RR Textiles",
"RS Brothers Textile",
"RS Brothers Retail India Pvt Ltd",
"RSM Shopping Mall",
"Rukmini Silks",
"RV Silk Sarees",
"Sachin Textiles",
"Sai Cloth Stores",
"Sai Ram Enterprises",
"Sairam Handlooms",
"Sairam Silks Showroom",
"Sai Sri Anugraha Silks",
"Sai Teja Silks",
"Sai Wedding Mall",
"Sangita Sarees",
"Santhosh Lifestyle",
"Sapthavarnika Silks",
"Saranam Shopping Mall",
"Saraswathi Textiles",
"Saravana Stores",
"Saroja Silks",
"Sayeed Textiles",
"Sharada Silks",
"Shakti Textiles",
"Shanmukha Srinivasa Textiles",
"Shivalaya Silks",
"Shivams Cloth Showroom",
"Shivani Fabrics",
"Shree Durga Saree Mandir",
"Shree Kalanjali Silks",
"Shri Tirumala Silks",
"Shristi Dristi Saree Centre",
"Siva Cut Pieces",
"SLN Swamy Shopping Mall",
"Someshwar Company",
"Sree Chandana Brothers",
"Sree Kamakshi Silks",
"Sree Sarada Silks",
"Sree Vara Lakshmi Shopping Mall",
"Sri Amma Silks",
"Sri Bhagyalakshmi Silks",
"Sri Chowdeshwari Silks",
"Sri Krishna Sarees",
"Sri Lakshmi Srinivasa Shopping Mall",
"Sri LVR Shopping Mall",
"Sri Narasimha Swamy Textiles",
"Srinivasa Silk House",
"Sri Raajeswari Silks",
"Sri Sai Silks",
"Sri Sapthagiri Textiles",
"Sri Shivani Shopping Mall",
"Sri Sindoor Silks",
"Sri Srinivasa Sarees",
"Sri Venkateswara Textiles",
"Sri Vinayaka Silks and Sarees",
"Sri Vishnu Creations",
"Swayamvaram Silks",
"Taj Enterprises",
"The Chennai Silks",
"Tulja Bhavani Shopping Mall",
"Urvasi Saree Mandir",
"Vaahini Shopping Mall",
"Vaibava Lakshmi Shopping Mall",
"Varalakshmi Silks",
"Vasavi Shopping Mall",
"Vasavi Silks Private Limited",
"Vastra Silks",
"Vastra Villa",
"Veenit Creation",
"Vijaya Silks",
"Vijayalakshmi Grandeur",
"Virinchi Silks",
"Vishala Shopping Mall",
"Vishnu Kanchi Creations",
"Vishnu Priya Silks",
"Vizag Texpro Private Limited",
"Voolapalli Silks",
"Vutla Krishnamurty and Sons",
"Yakkala Silks"
]# Insert without duplicates
for name in client_names:
    if not Client.objects(name=name):
        print('s')
        Client(name=name).save()

print("✅ Bulk clients imported")